college_majors = [
    "Calculus I",
    "Calculus II",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Computer Science",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Mathematics",
    "Physics",
    "Biology",
    "Science, Technology, and Society",
    "Chemistry",
    "Psychology",
    "Economics",
    "English",
    "History",
    "Political Science",
    "Sociology",
    "Anthropology",
    "Communication",
    "Journalism",
    "Art History",
    "Music",
    "Film Studies",
    "Theater",
    "Nursing",
    "Education",
    "Business Administration",
    "Marketing",
    "Finance",
    "Accounting",
    "International Relations",
    "Environmental Science",
    "Agriculture",
    "Architecture",
    "Graphic Design",
    "Fashion Design",
    "Criminal Justice",
    "Public Health",
    "Nutrition",
    "Social Work",
    "Philosophy",
    "Religious Studies"
    "Calculus"
]
months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December"
]
